app_homepage:
  path: /
  controller: App\Controller\DefaultController::index

app_movie_list:
  path: /movies
  controller: App\Controller\Movie\ListController::index

app_register:
  path: /register
  controller: App\Controller\User\RegistrationController::create
